language: python
env:
  - TOXENV=py27-django14-test
  - TOXENV=py27-django15-test
  - TOXENV=py27-django16-test
  - TOXENV=py27-django17-test
  - TOXENV=py27-django18-test
  - TOXENV=py27-django19-test
  - TOXENV=py33-django15-test
  - TOXENV=py33-django16-test
  - TOXENV=py33-django17-test
  - TOXENV=py33-django18-test
  - TOXENV=py34-django16-test
  - TOXENV=py34-django17-test
  - TOXENV=py34-django18-test
  - TOXENV=py34-django19-test
  - TOXENV=py27-flake
  - TOXENV=py33-flake
  - TOXENV=py34-flake
  - TOXENV=checkmanifest
install:
  - pip install coveralls tox>=2.1
script:
  - tox
after_script:
  - coveralls
sudo: false
